---
title: "Helpdesk responses"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(INBOtheme)
library(googlesheets4)

conflicted::conflicts_prefer(dplyr::filter)
```

# Tijdsreeks

```{r, message=FALSE}
# Get years
current_year <- year(Sys.Date())
prev_year <- current_year - 1

# Load data
responses_raw <- read_sheet(
  paste0("https://docs.google.com/spreadsheets/d/",
         "19ERZjnsKgxmJ0gyU9GH2i1nAjbsIdDCxougTxqNPJco/edit?usp=sharing")
  )

# Prepare data
data <- responses_raw %>%
  mutate(jaar = year(Timestamp),
         datum = date(Timestamp)) %>%
  arrange(Timestamp) %>%
  mutate(one = 1,
         cum_n = cumsum(one),
         .by = "jaar") %>%
  filter(jaar < current_year)
```

```{r}
data %>%
  count(jaar) %>%
  ggplot(aes(x = jaar, y = n)) +
    geom_bar(stat = "identity") +
    geom_text(aes(label = n), vjust = -0.3, colour = "black") +
    labs(x = "", y = "Aantal BMK helpdesk aanvragen") +
    theme_minimal()
```

# Analyse vorig jaar

```{r}
data_prev_year <- data %>%
  filter(jaar == prev_year)

ggplot(data_prev_year, aes(x = datum, y = cum_n)) +
  geom_line() +
  geom_point() +
  labs(x = "", y = "Cumulatief aantal BMK helpdesk aanvragen",
         title = paste("Verloop aanvragen", prev_year)) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
    theme_minimal()
```

```{r}
data_prev_year %>%
  count(Onderwerp) %>%
  mutate(Onderwerp = reorder(Onderwerp, n)) %>%
  ggplot() +
    geom_bar(aes(x = Onderwerp, y = n), stat = "identity", width = 0.5) +
    labs(x = "", y = "Aantal BMK helpdesk aanvragen",
         title = paste("Onderwerp aanvragen", prev_year)) +
    scale_x_discrete(labels = scales::label_wrap(25)) +
    coord_flip() +
    theme_minimal()
```

```{r}
data_prev_year %>%
  mutate(Status = ifelse(is.na(Status), "in behandeling", Status)) %>%
  count(Status) %>%
  mutate(Status = reorder(Status, n)) %>%
  ggplot() +
    geom_bar(aes(x = Status, y = n), stat = "identity", width = 0.5) +
    labs(x = "", y = "Aantal BMK helpdesk aanvragen",
         title = paste("Status aanvragen", prev_year)) +
    scale_x_discrete(labels = scales::label_wrap(20)) +
    coord_flip() +
    theme_minimal()
```
